name: eg-247
channels:
- defaults
dependencies:
- ca-certificates=2017.08.26=ha1e5d58_0
- certifi=2017.11.5=py35hd00889a_0
- libcxx=4.0.1=h579ed51_0
- libcxxabi=4.0.1=hebd6815_0
- libedit=3.1=hb4e282d_0
- libffi=3.2.1=h475c297_4
- ncurses=6.0=hd04f020_2
- openssl=1.0.2n=hdbc3d79_0
- pip=9.0.1=py35h33ce766_4
- python=3.5.4=he720263_23
- readline=7.0=hc1231fa_4
- setuptools=36.5.0=py35h52cde6a_0
- sqlite=3.20.1=h7e4c145_2
- tk=8.6.7=h35a86e2_3
- wheel=0.30.0=py35h5c0b906_1
- xz=5.2.3=h0278029_2
- zlib=1.2.11=hf3cbc9b_2
prefix: /Users/eechris/anaconda3/envs/eg-247

